export {default as Hero} from './Hero'
export {default as BioSection} from './Bio'
export {default as Services} from './Services'
export {default as Certification} from './Certification'
export {default as References} from './References'
export {default as Contact} from './Contact'